spring.application.name=bibliotec-api

spring.datasource.url=jdbc:postgresql://localhost:1026/bibliotec
spring.datasource.username=postgres
spring.datasource.password=ddspiv71

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
